"""'modelFile'

Revision ID: 193857c54fee   映射版本号
Revises: 
Create Date: 2021-12-18 15:57:27.743000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193857c54fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 需要创建的表
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('a_id', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.DATETIME(), nullable=True),
    sa.Column('alterTime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
