"""'modelFile'

Revision ID: 6ef4ff0ad062
Revises: 193857c54fee
Create Date: 2021-12-18 16:02:57.753000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef4ff0ad062'
down_revision = '193857c54fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('acreage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'acreage')
    # ### end Alembic commands ###
