"""'第五提交添加收入字段'

Revision ID: a89a5e7f070d
Revises: aadbe5b7eef0
Create Date: 2021-12-18 16:18:10.875000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89a5e7f070d'
down_revision = 'aadbe5b7eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('收入', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', '收入')
    # ### end Alembic commands ###
