"""'第四提交添加人口字段'

Revision ID: aadbe5b7eef0
Revises: 6ef4ff0ad062
Create Date: 2021-12-18 16:12:59.727000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadbe5b7eef0'
down_revision = '6ef4ff0ad062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('人口', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', '人口')
    # ### end Alembic commands ###
